name: dart_leaks
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0-182.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  weak_map: ^2.0.4
  uuid: ^3.0.6
  logging: ^1.0.2
  memory_tools:
    path: ../memory_tools
#    git:
#      url: git://github.com/polina-c/spikes.git
#      path: memory_tools

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter
