name: macros_example
environment:
  sdk: ^3.5.0-15.0.dev
publish_to: none

dependencies:
  macros: ^0.1.0


dependency_overrides:
  macros:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/macros
      ref: 3.5.0-15.0.dev
