name: disposable_macro
version: 0.0.1


environment:
  sdk: '>=3.5.0-36.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  macros: ^0.1.0-0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
