name: macro_disposable
version: 0.1.0

environment:
  sdk: '>=3.5.0-18.0.dev <4.0.0'
  flutter: '>=3.18.0-18.0.pre.54'

dependencies:
  macros: ^0.1.0-0
  meta: any
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  flutter_test:
    sdk: flutter
