name: macro_disposable
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.4.0-140.0.dev

dependencies:
  flutter:
    sdk: flutter
  meta: any

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
