name: macro_disposable
version: 0.1.0

environment:
  sdk: '>=3.5.0-18.0.dev <4.0.0'

dependencies:
  macros: ^0.1.0-0
  meta: any
  flutter_lints: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
