name: ai
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.2.0-134.0.dev

dependencies:
  langchain: ^0.0.12
  langchain_openai: ^0.0.12
  langchain_google: ^0.0.7+1
  langchain_chroma: ^0.0.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
