name: disposable
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0-134.0.dev

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  meta: any

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
